version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --short --client
      - echo Installing AWS IAM Authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin
      # Install Clair scanner
      - echo Installing Clair scanner...
      - curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 > clair-scanner
      - chmod +x clair-scanner
      - mv clair-scanner /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Start Clair vulnerability database update (optional, depends on your Clair setup)
#      - echo Updating Clair vulnerability database...
#      - <command-to-update-clair-db>

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo dckr_pat_mMU1e_gw9UAp3Q17JMqYE2Ifg6E | docker login --username mustafajafri --password-stdin
      - docker build -t eks-lab-5 . 
      - docker tag eks-lab-5:latest public.ecr.aws/c3x5e8o7/eks-lab-5:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c3x5e8o7
      - docker push public.ecr.aws/c3x5e8o7/eks-lab-5:latest || (echo "docker push failed" && exit 1)
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name kubernetes-lab-03
      - kubectl config current-context
      - kubectl get nodes
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f k8s-deployment.yml
      - kubectl replace --force -f k8s-deployment.yml
      - kubectl get deployment
